language: node_js

node_js:
  - "6"
  - "7"
  - "8"

cache: yarn

before_install:
  - yarn global add elm
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn test -- --no-timeouts

after_script:
  - greenkeeper-lockfile-upload

env:
  secure: ivQuJpCTEa12PEBIUsrELNfUu50tM5CvyTwcXHnDxSKwR55XbjvW7ePrjWeYE4mMilxcI9BFddThjuXh9fu3MF8GHnS8Qd87wIm3VjgN703Fo3tpos48pBVE2Y8V9NFhxbpKrRnBxO5D9JmXSP58cTp84Xl3FQEZMLZVeDH2LbowugmcIj1FCEyVTNQEE7z8XAwbHr+a5Grj33J5YAOHmdDPmOLF9UtsPBjzwXdNqm8rUZoPacEjnSA+dP1dXcvlwYtNyKutOvcuo7bHCDlSkR/l1KH1eFTUZsef3HAn68L76UrXvXf+tbxToViQzDZdiPDV0kG57wZgR3ZhVXJsAeArFUxZr1T2J8QU+sL56cmL8R5f0N5R+q7rEtP3XsIVgQbOKo67dPeQj+s8B73uzjpaZq76T24u+sFS1bjRs3ba6/PL24uTHwPohFJAIUrhHa+UE4b/BOa0XYy+qIswAzD/eYIQUJ9wps3JaeympULIpBe7LKXjT0pfl8RB4hm2W3s1II+IKTcyT1hj1A0UKfuOdwqFLaHHv4nsFnMbVSimuisWX3Gjr0I1MRyT/eIQbbjwbKDNpP96ofVgjw+biWDDLg2Wm7XsOFiA4xIWgmgK3q3iM1fod+lBivfHMlRLdYS4TfizYSZtpaaXoZUl9jijQADILojag81tXOP36cw=
