environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

cache:
 - "%LOCALAPPDATA%\\Yarn"

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - yarn global add elm
  - yarn

test_script:
  # Output useful info for debugging.
  - ps: where.exe elm-make
  - node --version
  - yarn --version
  # run tests
  - yarn test -- --no-timeouts

# Don't actually build.
build: off

notifications:
  - provider: GitHubPullRequest
