version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "javascript"
    directory: "/example"
    update_schedule: "daily"
  - package_manager: "elm"
    directory: "/example"
    update_schedule: "daily"
  - package_manager: "elm"
    directory: "/test"
    update_schedule: "daily"
